---
# task for dgnest.haproxy

- name: setup haproxy configuration
  become: true
  template: src="{{ item.src }}" dest="{{ item.dest }}"
  with_items: "{{ _haproxy_templates | default({}) }}"
  when: _haproxy_templates is defined
  tags:
    - reload_haproxy
  notify:
    - reload haproxy
