---
# task file for dgnest.haproxy

- name: Update package repositories
  become: true
  apt:
    update_cache: True
  when: ansible_distribution == "Ubuntu"
  tags:
    - apt
    - update_cache

- name: Install haproxy package dependencies
  become: true
  apt:
    name: "{{ item }}"
    state: present
  register: install_haproxy_package_dependencies
  when: _haproxy_package_dependencies is defined
  with_items: _haproxy_package_dependencies
  tags:
    - apt
    - dependencies
- debug: var=install_haproxy_package_dependencies.stdout_lines

- name: Install haproxy dependencies
  become: true
  apt:
    name: "{{ item.name }}"
    state: present
  register: install_haproxy_dependencies
  when: _haproxy_dependencies is defined
  with_items: _haproxy_dependencies
  tags:
    - apt
    - dependencies
- debug: var=install_haproxy_dependencies.stdout_lines
