---
# task for dgnest.haproxy

- name: Update package repositories
  become: true
  apt:
    update_cache: True
  when: ansible_distribution == "Ubuntu"
  tags:
    - apt
    - update_cache

- name: Install haproxy
  become: true
  package:
    name: "{{ _haproxy_name_package }}"
    state: present
  tags:
    - haproxy
