---
# task for dgnest.haproxy

- include: install.d/CentOS.yaml
  when: ansible_distribution == "CentOS"
  tags:
    - haproxy

- include: install.d/Ubuntu.yaml
  when: ansible_distribution == "Ubuntu"
  tags:
    - haproxy