---

# task file for dgnest.haproxy

- name: Ensure apt cache is up to date
  apt:
    update_cache: true


- name: Install haproxy dependencies
  apt: name={{ item }} state=present update_cache=true
  with_items: _haproxy_packages
  when: _haproxy_packages is defined
  tags:
    - haproxy


- name: Install haproxy
  when: ansible_os_family == 'Debian'
  become: true
  apt:
    name: "{{ _haproxy_name_package }}"
    state: present
    update_cache: true
    cache_valid_time: 3600
  tags:
    - haproxy
